name: Go Analysis
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v1.0.0
        with:
          go-version: 1.21.x
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true
